TravelBlogWeb/TravelBlogWeb/Controllers/AddBlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelBlogWeb.Controllers
{
    public class AddBlogController : Controller
    {
        // GET: AddBlog
        public ActionResult Index()
        {
            return View();
        }
    }
}

TravelBlogWeb/TravelBlogWeb/Controllers/SingleBlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBlogWeb.Entity;
using TravelBlogWeb.Entity.Data;
using TravelBlogWeb.Entity.Interfaces;
using TravelBlogWeb.Models;



namespace TravelBlogWeb.Controllers
{
    public class SingleBlogController : Controller
    {
        BlogPostProcess blogPostProcess = new BlogPostProcess();
        CommentProcess commentProcess = new CommentProcess();
        PartialProcess partialProcess = new PartialProcess();
        BlogLikeProcess blogLikeProcess = new BlogLikeProcess();
        DataContext db = new DataContext();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowBlog(int id)
        {
            var blogComments = commentProcess.GetBlogComments(id);
            int commentsCount = blogComments.Count();
            ViewData["commentCount"] = commentsCount;
            ViewData["Comments"] = blogComments;
            ViewData["currentBlogId"] = id;
            var blog = blogPostProcess.Get(id);
            var populars = partialProcess.GetPopulars();
            var latests = partialProcess.GetLatests();
            ViewBag.populars = populars;
            ViewBag.latests = latests;
            ViewBag.blogId = id;
            ViewBag.likeCount = blogLikeProcess.GetBlogCount(id);
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);


            var likeState = db.BlogLikes.FirstOrDefault(like => like.BlogPostId == id && like.UserId == userId);

            bool isLiked;
            if (likeState == null)
            {
                isLiked = false;
            }
            else
            {
                isLiked = true;

            }
            ViewBag.isLiked = isLiked;

            return View(blog);
        }
        [HttpPost]
        public ActionResult AddComment()
        {
            string commentText = Request.Form["commentText"];
            int blogId = Convert.ToInt32(Request.Form["blogId"]);
            BlogComment newComment = new BlogComment
            {
                Comment = commentText,
                CreationDate = DateTime.Now,
                UserId = Convert.ToInt32(HttpContext.Session["userId"]),
                IsActive = false,
                BlogPostId = blogId
            };

            commentProcess.Add(newComment);
            return View();
        }

        [HttpPost]

        public ActionResult Like()
        {
            int currentId = Convert.ToInt32(Request.Form["likeblogId"]);

            BlogLike newLike = new BlogLike
            {
                UserId = Convert.ToInt32(HttpContext.Session["userId"]),
                BlogPostId = currentId
            };

            blogLikeProcess.Add(newLike);

            return RedirectToAction("Index", "Cities");

        }
        [HttpPost]
        public ActionResult Dislike()
        {
            int currentId = Convert.ToInt32(Request.Form["likeblogId"]);
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);
            var dislikedLike = db.BlogLikes.FirstOrDefault(x => x.BlogPostId == currentId && x.UserId ==userId);

            int dislikedId = Convert.ToInt32(dislikedLike.Id);
            string result = blogLikeProcess.Dislike(dislikedId);

            ViewBag.ResultMessage = result;

            return RedirectToAction("Index", "Cities");
        }


    }
}

TravelBlogWeb/TravelBlogWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TravelBlogWeb.Entity;
using TravelBlogWeb.Entity.Data;
using TravelBlogWeb.Models;
using System.Net;
using System.Web.Helpers;


namespace TravelBlogWeb.Controllers
{
    public class UserController : Controller
    {
        UserProcess userProcess = new UserProcess();
        BlogPostProcess blogPostProcess = new BlogPostProcess();
        PartialProcess partialProcess = new PartialProcess();
        BlogCityRelationProcess blogCityRelationProcess = new BlogCityRelationProcess();
        DataContext db = new DataContext();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string email, string password)
        {
            var user = db.Users.FirstOrDefault(x => x.Email == email && x.Password == password);
            if (user != null)
            {

                FormsAuthentication.SetAuthCookie(email, true);

                HttpContext.Session["userEmail"] = email;
                HttpContext.Session["name"] = user.Name;
                HttpContext.Session["img"] = user.Image;
                HttpContext.Session["userId"] = user.Id;



                if (user.IsAdmin == true)
                {
                    return RedirectToAction("Index", "Panel");

                }

                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewData["Message"] = "Email or password is incorrect!";
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        public ActionResult SignUp()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignUp(User model)
        {
            try
            {
                string name = Request.Form["name"];
                string email = Request.Form["email"];
                string password = Request.Form["password"];
                DateTime creationDate = DateTime.Now;


                User newUser = new User
                {
                    Name = name,
                    Email = email,
                    Password = password,
                    CreationDate = creationDate,
                    IsAdmin = false
                };

                userProcess.Add(newUser);


                return View();
            }
            catch (Exception ex)
            {
                return View("Error");
            }

        }
        public ActionResult MyBlogs()
        {
            List<BlogPost> myBlogs = new List<BlogPost>();
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);
            myBlogs = blogPostProcess.GetMyBlogs(userId);
            var populars = partialProcess.GetPopulars();
            var latests = partialProcess.GetLatests();
            ViewBag.populars = populars;
            ViewBag.latests = latests;
            return View(myBlogs);
        }
        [HttpGet]
        public ActionResult EditMyBlog(int blogId)
        {

            var cities = blogCityRelationProcess.GetAll();
            ViewBag.cities = cities;

            var editedBlog = blogPostProcess.Get(blogId);
            return View(editedBlog);
        }
        [HttpPost]
        public ActionResult EditMyBlog(BlogPost model)
        {
            try
            {
                string title = Request.Form["blogTitle"];
                string content = Request.Form["editor"];
                string image = Request.Form["blogImage"];
                int selectedCityId = int.Parse(Request.Form["citiesList"]);
                int editedBlogId = int.Parse(Request.Form["blogId"]);

                BlogPost editedBlogPost = new BlogPost
                {
                    Title = title,
                    Content = content,
                    Image=image,
                    UserId = Convert.ToInt32(HttpContext.Session["userId"])
                };

                blogPostProcess.Update(editedBlogPost, editedBlogId);

                var editedRelation = db.CityBlogRelations.FirstOrDefault(x => x.BlogPostId == editedBlogId);
                CityBlogRelation cityBlogRelation = new CityBlogRelation
                {
                    BlogPostId = editedBlogId,
                    CityId = selectedCityId,
                };
                blogCityRelationProcess.Update(cityBlogRelation, editedRelation.Id);
                

                ViewData["successMessage"] = "Your blog updated successfully!";

                return RedirectToAction("MyBlogs");
            }
            catch (Exception ex)
            {

                return View("Error");
            }
        }


        
        public ActionResult MyProfile(int id)
        {
            var user = userProcess.Get(id);
            return View(user);

        }

        [HttpPost]
        public ActionResult EditProfile()
        {
            try
            {
                string name = Request.Form["userName"];
                string email = Request.Form["userEmail"];
                string password = Request.Form["userPassword"];

                
                int userId = int.Parse(Request.Form["userId"]);

                User editedUser = new User
                { 
                    Id=userId,
                    Name = name,
                    Email = email,
                    Password = password
                };
                userProcess.Update(editedUser, userId);

                ViewData["successMessage"] = "user updated successfully!";

                return RedirectToAction("Index", "Home");
            }

            catch (Exception ex)
            {
                return View("Error");
            }
        }


        public ActionResult EditMyProfile(string eMail)
        {
            var user = userProcess.Get(eMail);
            return View(user);
        }

        [HttpPost]
        public ActionResult EditMyProfile()
        {
            try
            {
                string name = Request.Form["userName"];
                string email = Request.Form["userEmail"];
                string password = Request.Form["userPassword"];


                int userId = Convert.ToInt32(HttpContext.Session["userId"]);

                User editedUser = new User
                {
                    Id = userId,
                    Name = name,
                    Email = email,
                    Password = password
                };
                userProcess.Update(editedUser, userId);

                ViewData["successMessage"] = "user updated successfully!";

                return RedirectToAction("Index", "Home");
            }

            catch (Exception ex)
            {

                return View("Error");
            }
        }

    }
}

TravelBlogWeb/TravelBlogWeb/Views/Shared/_Layout.cshtml
@{
    var userEmail = HttpContext.Current.Session["userEmail"] as string;
    var userName = HttpContext.Current.Session["name"] as string;
    var userImg = HttpContext.Current.Session["img"] as string;
    var userId = HttpContext.Current.Session["userId"] as string;
}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Anatolian Vibes</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/Zenblog/assets/img/favicon.png" rel="icon">
    <link href="~/Zenblog/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Zenblog/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Zenblog/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Zenblog/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/Zenblog/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Zenblog/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS Files -->
    <link href="~/Zenblog/assets/css/variables.css" rel="stylesheet">
    <link href="~/Zenblog/assets/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- =======================================================
    * Template Name: ZenBlog
    * Updated: Sep 18 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/zenblog-bootstrap-blog-template/
    * Author: BootstrapMade.com
    * License: https:///bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="/" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="~/Zenblog/assets/img/logo.png" alt=""> -->
                <h1>Anatolian Vibes</h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Cities", "Index", "Cities")
                    </li>

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>


                    @{ if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.ActionLink("Add Blog", "AddBlog", "Home")
                            </li>
                            <li>
                                @Html.ActionLink("My Blogs", "MyBLogs", "User")
                            </li>
                            <li>

                                @Html.ActionLink("Profile", "EditMyProfile", "User", new { eMail = userEmail }, null)

                            </li>
                            <li>
                                @Html.ActionLink("Logout", "Logout", "User")
                            </li>
                        }
                        else
                        {
                            <li class="dropdown">
                                <a style="cursor:pointer;"><span>Login /Sign Up</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                                <ul>
                                    <li>
                                        @Html.ActionLink("Login", "Login", "User")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Sign Up", "SignUp", "User")
                                    </li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
            </nav><!-- .navbar -->

            <div class="position-relative">


                <a style="display:none;" href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
                <i style="display:none;" class="bi bi-list mobile-nav-toggle"></i>

                <!-- ======= Search Form ======= -->
                <div class="search-form-wrap js-search-form-wrap" style="display:none">
                    <form action="search-result.html" class="search-form">
                        <span class="icon bi-search"></span>
                        <input type="text" placeholder="Search" class="form-control">
                        <button class="btn js-search-close"><span class="bi-x"></span></button>
                    </form>
                </div><!-- End Search Form -->
                <!-- ======= User Profile ======= -->

                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <div class="container mt-3 text-center ">
                            <div class="rounded-circle overflow-hidden mx-auto" style="width: 50px; height: 50px;">
                                <img src="@userImg" alt="Image" class="w-100 h-100 object-fit-cover">
                            </div>
                            <p>@userName</p>
                        </div>
                    }
                    else
                    {
                        <div class="container mt-3 text-center ">
                            <div class="rounded-circle overflow-hidden mx-auto" style="width: 50px; height: 50px;">
                                <img src="https://via.placeholder.com/200" alt="Image" class="w-100 h-100 object-fit-cover">
                            </div>
                            <p>Guest</p>
                        </div>
                    }

                }


                <!-- End End User Profile -->
            </div>

        </div>

    </header><!-- End Header -->

    @RenderBody()

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">

                <div class="row g-5">
                    <div class="col-lg-10">
                        <h3 class="footer-heading">About Anatolian Vibes</h3>
                        <p>Discover the beauty and diversity of Turkey's 81 provinces through our blog. As passionate travelers and storytellers, we aim to bring you captivating narratives and stunning visuals that showcase the rich history, vibrant culture, and breathtaking landscapes of each region.</p>
                        <p><a href="Home/About" class="footer-link-more">Learn More</a></p>
                    </div>
                    <div class="col-8 col-lg-2">
                        <h3 class="footer-heading">Navigation</h3>
                        <ul class="footer-links list-unstyled">
                            <li>
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Cities", "Index", "Cities")
                            </li>

                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>
                                @Html.ActionLink("Contact", "Contact", "Home")
                            </li>

                        </ul>
                    </div>


                </div>
            </div>
        </div>

        <div class="footer-legal">
            <div class="container">

                <div class="row justify-content-between">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <div class="copyright">
                            © Copyright <strong><span>ZenBlog</span></strong>. All Rights Reserved
                        </div>

                        <div class="credits">
                            <!-- All the links in the footer should remain intact. -->
                            <!-- You can delete the links only if you purchased the pro version. -->
                            <!-- Licensing information: https://bootstrapmade.com/license/ -->
                            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
                            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                            <a target="_blank" href="https://twitter.com/" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a target="_blank" href="https://facebook.com/" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a target="_blank" href="https://instagram.com/" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a target="_blank" href="https://skype.com/" class="google-plus"><i class="bi bi-skype"></i></a>
                            <a target="_blank" href="https://linkedin.com/" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

    </footer>

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/Zenblog/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Zenblog/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/Zenblog/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/Zenblog/assets/vendor/aos/aos.js"></script>
    <script src="~/Zenblog/assets/vendor/php-email-form/validate.js"></script>



    <!-- Template Main JS File -->
    <script src="~/Zenblog/assets/js/main.js"></script>

</body>

</html>

TravelBlogWeb/TravelBlogWeb/Views/Shared/_SidebarPartial.cshtml
<div class="col-md-3">
    <!-- ======= Sidebar ======= -->
    <div class="aside-block">

        <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Popular</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Latest</button>
            </li>
        </ul>

        <div class="tab-content" id="pills-tabContent">

            <!-- Popular -->
            <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">
                @foreach (var item in ViewBag.populars)
                {

                    <div class="post-entry-1 border-bottom">
                        <div class="post-meta"><span>@item.CreationDate</span></div>
                        <h2 class="mb-2"><a href="@Url.Action("ShowBlog", "SingleBlog", new { id = item.Id })">@item.Title</a></h2>
                        <span class="author mb-3 d-block">@item.User.Name</span>
                    </div>
                }


            </div>

            <!-- Latest -->


            <div class="tab-pane fade show active" id="pills-latest" role="tabpanel" aria-labelledby="pills-latests-tab">
                


            @foreach (var item in ViewBag.latests)
            {

                <div class="post-entry-1 border-bottom">
                    <div class="post-meta"> <span>@item.CreationDate</span></div>
                    <h2 class="mb-2"><a href="@Url.Action("ShowBlog", "SingleBlog", new { id = item.Id })">@item.Title</a></h2>
                    <span class="author mb-3 d-block">@item.User.Name</span>
                </div>
            }
            </div>




        </div> <!-- End Latest -->

    </div>
</div>

TravelBlogWeb/TravelBlogWeb/Views/Shared/_UserLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_UserLayout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>