TravelBlogWeb/TravelBlogWeb/Controllers/PanelPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBlogWeb.Entity;

namespace TravelBlogWeb.Controllers
{
    [Authorize]
    public class PanelPartialController : Controller
    {
        UserProcess userProccess = new UserProcess();
        
        public ActionResult AcountSideLeftBar()
        {
            var user = userProccess.Get((int)(HttpContext.Session["userId"]));
            return PartialView(user);
        }

       
    }
}

TravelBlogWeb/TravelBlogWeb/Controllers/SingleBlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBlogWeb.Entity;
using TravelBlogWeb.Entity.Data;
using TravelBlogWeb.Entity.Interfaces;
using TravelBlogWeb.Models;



namespace TravelBlogWeb.Controllers
{
    public class SingleBlogController : Controller
    {
        BlogPostProcess blogPostProcess = new BlogPostProcess();
        CommentProcess commentProcess = new CommentProcess();
        PartialProcess partialProcess = new PartialProcess();
        BlogLikeProcess blogLikeProcess = new BlogLikeProcess();
        DataContext db = new DataContext();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowBlog(int id)
        {
            var blogComments = commentProcess.GetBlogComments(id);
            int commentsCount = blogComments.Count();
            ViewData["commentCount"] = commentsCount;
            ViewData["Comments"] = blogComments;
            ViewData["currentBlogId"] = id;
            var blog = blogPostProcess.Get(id);
            var populars = partialProcess.GetPopulars();
            var latests = partialProcess.GetLatests();
            ViewBag.populars = populars;
            ViewBag.latests = latests;
            ViewBag.blogId = id;
            ViewBag.likeCount = blogLikeProcess.GetBlogCount(id);
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);


            var likeState = db.BlogLikes.FirstOrDefault(like => like.BlogPostId == id && like.UserId == userId);

            bool isLiked;
            if (likeState == null)
            {
                isLiked = false;
            }
            else
            {
                isLiked = true;

            }
            ViewBag.isLiked = isLiked;

            return View(blog);
        }
        [HttpPost]
        public ActionResult AddComment()
        {
            string commentText = Request.Form["commentText"];
            int blogId = Convert.ToInt32(Request.Form["blogId"]);
            BlogComment newComment = new BlogComment
            {
                Comment = commentText,
                CreationDate = DateTime.Now,
                UserId = Convert.ToInt32(HttpContext.Session["userId"]),
                IsActive = false,
                BlogPostId = blogId
            };

            commentProcess.Add(newComment);
            return View();
        }

        [HttpPost]

        public ActionResult Like()
        {
            int currentId = Convert.ToInt32(Request.Form["likeblogId"]);

            BlogLike newLike = new BlogLike
            {
                UserId = Convert.ToInt32(HttpContext.Session["userId"]),
                BlogPostId = currentId
            };

            blogLikeProcess.Add(newLike);

            return RedirectToAction("Index", "Cities");

        }
        [HttpPost]
        public ActionResult Dislike()
        {
            int currentId = Convert.ToInt32(Request.Form["likeblogId"]);
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);
            var dislikedLike = db.BlogLikes.FirstOrDefault(x => x.BlogPostId == currentId && x.UserId ==userId);

            int dislikedId = Convert.ToInt32(dislikedLike.Id);
            string result = blogLikeProcess.Dislike(dislikedId);

            ViewBag.ResultMessage = result;

            return RedirectToAction("Index", "Cities");
        }


    }
}

TravelBlogWeb/TravelBlogWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TravelBlogWeb.Entity;
using TravelBlogWeb.Entity.Data;
using TravelBlogWeb.Models;
using System.Net;
using System.Web.Helpers;


namespace TravelBlogWeb.Controllers
{
    public class UserController : Controller
    {
        UserProcess userProcess = new UserProcess();
        BlogPostProcess blogPostProcess = new BlogPostProcess();
        PartialProcess partialProcess = new PartialProcess();
        BlogCityRelationProcess blogCityRelationProcess = new BlogCityRelationProcess();
        DataContext db = new DataContext();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string email, string password)
        {
            var user = db.Users.FirstOrDefault(x => x.Email == email && x.Password == password);
            if (user != null)
            {

                FormsAuthentication.SetAuthCookie(email, true);

                HttpContext.Session["userEmail"] = email;
                HttpContext.Session["name"] = user.Name;
                HttpContext.Session["img"] = user.Image;
                HttpContext.Session["userId"] = user.Id;



                if (user.IsAdmin == true)
                {
                    return RedirectToAction("Index", "Panel");

                }

                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewData["Message"] = "Email or password is incorrect!";
                return View();
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        public ActionResult SignUp()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignUp(User model)
        {
            try
            {
                string name = Request.Form["name"];
                string email = Request.Form["email"];
                string password = Request.Form["password"];
                DateTime creationDate = DateTime.Now;


                User newUser = new User
                {
                    Name = name,
                    Email = email,
                    Password = password,
                    CreationDate = creationDate,
                    IsAdmin = false
                };

                userProcess.Add(newUser);


                return View();
            }
            catch (Exception ex)
            {
                return View("Error");
            }

        }
        public ActionResult MyBlogs()
        {
            List<BlogPost> myBlogs = new List<BlogPost>();
            int userId = Convert.ToInt32(HttpContext.Session["userId"]);
            myBlogs = blogPostProcess.GetMyBlogs(userId);
            var populars = partialProcess.GetPopulars();
            var latests = partialProcess.GetLatests();
            ViewBag.populars = populars;
            ViewBag.latests = latests;
            return View(myBlogs);
        }
        [HttpGet]
        public ActionResult EditMyBlog(int blogId)
        {

            var cities = blogCityRelationProcess.GetAll();
            ViewBag.cities = cities;

            var editedBlog = blogPostProcess.Get(blogId);
            return View(editedBlog);
        }
        [HttpPost]
        public ActionResult EditMyBlog(BlogPost model)
        {
            try
            {
                string title = Request.Form["blogTitle"];
                string content = Request.Form["editor"];
                string image = Request.Form["blogImage"];
                int selectedCityId = int.Parse(Request.Form["citiesList"]);
                int editedBlogId = int.Parse(Request.Form["blogId"]);

                BlogPost editedBlogPost = new BlogPost
                {
                    Title = title,
                    Content = content,
                    Image=image,
                    UserId = Convert.ToInt32(HttpContext.Session["userId"])
                };

                blogPostProcess.Update(editedBlogPost, editedBlogId);

                var editedRelation = db.CityBlogRelations.FirstOrDefault(x => x.BlogPostId == editedBlogId);
                CityBlogRelation cityBlogRelation = new CityBlogRelation
                {
                    BlogPostId = editedBlogId,
                    CityId = selectedCityId,
                };
                blogCityRelationProcess.Update(cityBlogRelation, editedRelation.Id);
                

                ViewData["successMessage"] = "Your blog updated successfully!";

                return RedirectToAction("MyBlogs");
            }
            catch (Exception ex)
            {

                return View("Error");
            }
        }


        
        public ActionResult MyProfile(int id)
        {
            var user = userProcess.Get(id);
            return View(user);

        }

        [HttpPost]
        public ActionResult EditProfile()
        {
            try
            {
                string name = Request.Form["userName"];
                string email = Request.Form["userEmail"];
                string password = Request.Form["userPassword"];

                
                int userId = int.Parse(Request.Form["userId"]);

                User editedUser = new User
                { 
                    Id=userId,
                    Name = name,
                    Email = email,
                    Password = password
                };
                userProcess.Update(editedUser, userId);

                ViewData["successMessage"] = "user updated successfully!";

                return RedirectToAction("Index", "Home");
            }

            catch (Exception ex)
            {
                return View("Error");
            }
        }


        public ActionResult EditMyProfile(string eMail)
        {
            var user = userProcess.Get(eMail);
            return View(user);
        }

        [HttpPost]
        public ActionResult EditMyProfile()
        {
            try
            {
                string name = Request.Form["userName"];
                string email = Request.Form["userEmail"];
                string password = Request.Form["userPassword"];


                int userId = Convert.ToInt32(HttpContext.Session["userId"]);

                User editedUser = new User
                {
                    Id = userId,
                    Name = name,
                    Email = email,
                    Password = password
                };
                userProcess.Update(editedUser, userId);

                ViewData["successMessage"] = "user updated successfully!";

                return RedirectToAction("Index", "Home");
            }

            catch (Exception ex)
            {

                return View("Error");
            }
        }

    }
}

TravelBlogWeb/TravelBlogWeb/Views/Panel/ApprovedComments.cshtml
@model List<TravelBlogWeb.Models.BlogComment>
@{
    ViewBag.Title = "PendingComments";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<div class="content-page">
    <div class="content">

        <div class="container mt-4">
            <h2>Approved Comments</h2>
            <table class="table table-bordered light-theme text-black">
                <thead class="text-center">
                    <tr>
                        <th>Blog Id</th>
                        <th>Blog Name</th>
                        <th>User Id</th>
                        <th>User Name</th>
                        <th>Comment</th>
                        <th>Settings</th>
                        <th>Comment Date</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.BlogPost.Id</td>
                            <td>@item.BlogPost.Title</td>
                            <td>@item.User.Name</td>
                            <td>@item.User.Id</td>
                            <td>@item.Comment</td>
                            <td>@item.CreationDate</td>
                            <td>
                                <form class="mt-2" action="@Url.Action("DeleteComment")" method="post"  >
                                    <input class="d-none" type="text" name="commentId" value="@item.Id"/>
                                    <button type="submit" class="btn btn-warning">Set Passive</button>
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>




    </div>

</div>

TravelBlogWeb/TravelBlogWeb/Views/Panel/BlogsPanel.cshtml
@model List<TravelBlogWeb.Models.BlogPost>

@{
    ViewBag.Title = "BlogsPanel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<div class="content-page">
    <div class="content">

        <div class="container mt-4">
            <h2>Blogs</h2>
            <table class="table table-bordered light-theme text-black">
                <thead class="text-center">
                    <tr>
                        <th>Blog Id</th>
                        <th>Blog Title</th>
                        <th>Blog Content</th>
                        <th>Author Name</th>
                        <th>Blog Creation Date</th>
                        <th>Blog Image</th>
                        <th>isActive</th>
                        <th>Settings</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Content</td>
                            <td>@item.User.Name</td>
                            <td>@item.CreationDate</td>
                            <td>
                                <img height="70px;" width="70px;" src="@item.Image" alt="Alternate Text" />
                            </td>
                            @{if (@item.IsDeleted)
                                {
                                    <td class="bg-danger text-white ">
                                        Passive
                                    </td>
                                }
                                else
                                {

                                    <td class="bg-success text-white">
                                        Active
                                    </td>
                                }

                            }

                            <td>
                                <a class="btn btn-info" href="@Url.Action("ShowBlog", "SingleBlog", new { id = @item.Id })">View</a>
                                <a class="btn btn-warning mt-1" href="@Url.Action("EditMyBlog", "User", new { blogId = @item.Id })">Edit</a>
                                <form class="mt-2" action="@Url.Action("DeleteBlog")" method="post">
                                    <input class="d-none" type="text" name="blogId" value="@item.Id" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>




    </div>

</div>

TravelBlogWeb/TravelBlogWeb/Views/Panel/Index.cshtml
@model TravelBlogWeb.Models.PanelHomeModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">

                <h2>Index - Hoşgeldin @HttpContext.Current.User.Identity.Name</h2>
                
                <div style="cursor:pointer;" class="col-2" onclick="window.location.href='/Panel/UsersPanel'">
                    <div class="card div-hover">
                        <div class="card-header">
                            <h3>Users</h3>
                        </div>
                        <div class="card-body text-center">
                            <i class="fa fa-users text-success" style="font-size:50px"></i> &nbsp;
                            <b class="text-success" style="font-size:56px">@Model.UserCount</b>
                        </div>
                    </div>
                </div>
                <div style="cursor:pointer;" class="col-2" onclick="window.location.href='/Panel/BlogsPanel'">
                    <div class="card div-hover" >
                        <div class="card-header">
                            <h3>Blogs</h3>
                        </div>
                        <div class="card-body text-center">
                            <i class="fa-solid fa-file-lines text-primary" style="font-size:50px" ></i> &nbsp;
                            <b class="text-primary" style="font-size:56px">@Model.BlogCount</b>
                        </div>
                    </div>
                </div>
                <div style="cursor:pointer;" class="col-3" onclick="window.location.href='/Panel/ApprovedComments'">
                    <div class="card div-hover">
                        <div class="card-header">
                            <h3>Approved Comments</h3>
                        </div>
                        <div class="card-body text-center">
                            <i class="fa-solid fa-comment text-warning" style="font-size:50px"></i> &nbsp;
                            <b class="text-warning" style="font-size:56px">@Model.ApprovedCommentsCount</b>
                        </div>
                    </div>
                </div>
                <div style="cursor:pointer;" class="col-3" onclick="window.location.href='/Panel/PendingComments'">
                    <div class="card div-hover">
                        <div class="card-header">
                            <h3>Pending Comments</h3>
                        </div>
                        <div class="card-body text-center">
                            <i class="fa-solid fa-comment-slash text-warning" style="font-size:50px"></i> &nbsp;
                            <b class="text-warning" style="font-size:56px">@Model.PendingCommentsCount</b>
                        </div>
                    </div>
                </div>
                <div style="cursor:pointer;" class="col-2" onclick="window.location.href='/Panel/Likes'">
                    <div class="card div-hover">
                        <div class="card-header">
                            <h3>Total Likes</h3>
                        </div>
                        <div class="card-body text-center">
                            <i class="fa-solid fa-heart text-danger" style="font-size:50px"></i> &nbsp;
                            <b class="text-danger" style="font-size:56px">@Model.LikesCount</b>
                        </div>
                    </div>
                </div>


                @*<div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3>Last Add Products</h3>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Stock</th>
                                <th>Price</th>
                                <th>Status</th>
                                <th>Settings</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LastAddProduct)
                            {
                                i++;
                                <tr>
                                    <td>@i</td>
                                    <td>@item.Name</td>
                                    <td>@item.Stock Adet</td>
                                    <td>@item.Price.ToString("c")</td>
                                    <td>
                                        <span class="badge bg-@(item.IsStatus?"success":"danger")">
                                            @(item.IsStatus?"Active":"Passive")
                                        </span>
                                    </td>

                                    <td>
                                        <a href="~/Product/Edit/@item.Id" class="btn btn-primary btn-sm">
                                            <i class="fa fa-cogs"></i> &nbsp;
                                            Edit
                                        </a>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3>Best Seller Products</h3>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Stock</th>
                                <th>Price</th>
                                <th>Status</th>
                                <th>Quantity</th>
                                <th>Settings</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.BestSellProduct)
                            {
                                j++;
                                <tr>
                                    <td>@j</td>
                                    <td>@item.Name</td>
                                    <td>@item.Stock Adet</td>
                                    <td>@item.Price.ToString("c")</td>
                                    <td>
                                        <span class="badge bg-@(item.IsStatus?"success":"danger")">
                                            @(item.IsStatus?"Active":"Passive")
                                        </span>
                                    </td>
                                    <td>
                                        @{ int quantity = 0;}
                                        @for (int k = 0; k < Model.ProductQuantity.GetLength(0); k++)
                                        {
                                            if (Model.ProductQuantity[k, 0] == item.Id)
                                            {
                                                quantity = Model.ProductQuantity[k, 1];
                                                break;
                                            }
                                        }
                                        @quantity Adet
                                    </td>
                                    <td>
                                        <a href="~/Product/Edit/@item.Id" class="btn btn-primary btn-sm">
                                            <i class="fa fa-cogs"></i> &nbsp;
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        @foreach (var item in Model.Categories)
        {
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3>@item.Name</h3>
                    </div>
                    <div class="card-body">
                        @Html.Action("CategoryProduct", "PanelPartial", new { id = item.Id })
                    </div>
                </div>
            </div>
        }*@

                @*<div class="row">
            <div class="col-3">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
                        Panel
                    </a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="~/Role/Index" class="list-group-item list-group-item-action">Role List</a>
                        <a href="~/User/Index" class="list-group-item list-group-item-action">User List</a>
                        <a href="~/Category/Index" class="list-group-item list-group-item-action">Category List</a>
                        <a href="~/Product/Index" class="list-group-item list-group-item-action">Product List</a>
                        <a href="~/Slider/Index" class="list-group-item list-group-item-action">Slider List</a>

                    }
                    <a href="~/Home/Index" class="list-group-item list-group-item-action">Web Site</a>
                </div>
            </div>
        </div>*@
            </div>
        </div>
    </div>
</div>

TravelBlogWeb/TravelBlogWeb/Views/Panel/Likes.cshtml
@model List<TravelBlogWeb.Models.BlogLike>
@{
    ViewBag.Title = "Likes";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<div class="content-page">
    <div class="content">

        <div class="container mt-4">
            <h2>User Likes</h2>
            <table class="table table-bordered light-theme text-black">
                <thead class="text-center">
                    <tr>
                        <th>Blog Id</th>
                        <th>Blog Name</th>
                        <th>User Id</th>
                        <th>User Name</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.BlogPost.Id</td>
                            <td>@item.BlogPost.Title</td>
                            <td>@item.User.Name</td>
                            <td>@item.User.Id</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>




    </div>

</div>

TravelBlogWeb/TravelBlogWeb/Views/Panel/UsersPanel.cshtml
@model List<TravelBlogWeb.Models.User>

@{
    ViewBag.Title = "UsersPanel";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<div class="content-page">
    <div class="content">

        <div class="container mt-4">
            <h2>Users</h2>
            <table class="table table-bordered light-theme text-black">
                <thead class="text-center">
                    <tr>
                        <th>User Id</th>
                        <th>Name</th>
                        <th>Password</th>
                        <th>Blog Creation Date</th>
                        <th>Image</th>
                        <th>Role</th>
                        <th>Activity</th>
                        <th>Settings</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Password</td>
                            <td>@item.CreationDate</td>
                            <td><img height="80px" src="@item.Image " alt="Alternate Text" /> </td>
                            @{if (@item.IsAdmin)
                                {
                                    <td>
                                        <a class="btn-success text-white btn"> Admin </a>

                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <a style="background-color: black;" class="btn text-white">User </a>
                                    </td>

                                }
                            }
                            @{if (@item.IsDeleted)
                                {
                                    <td class="bg-danger text-white">
                                        Passive
                                    </td>
                                }
                                else
                                {

                                    <td class="bg-success text-white">
                                        Active
                                    </td>
                                }

                            }

                            <td class="mx-1">
                                <a class="btn btn-warning" href="@Url.Action("MyProfile", "User", new { id = @item.Id })">Edit</a>
                                <form class="mt-2" action="@Url.Action("DeleteUser")" method="post">
                                    <input class="d-none" type="text" name="userIddd" value="@item.Id" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>




    </div>
</div>